apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: hello
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: hashicorp/http-echo:0.2.3
        args: ["-text=hello-v2"]
        ports:
        - containerPort: 5678
  strategy:
    canary:
      canaryService: hello-canary
      stableService: hello-stable
      trafficRouting:
        istio:
          virtualService:
            name: hello
            routes:
            - http # Matches the route name in the VirtualService
      steps:
      - setWeight: 10
      - pause: {}
      - setWeight: 25
      - pause: {}
      - setWeight: 50
      - pause: {}

