apiVersion: v1
kind: Service
metadata:
  name: hello-stable
  labels:
    app: hello
spec:
  selector:
    app: hello
    # Rollouts controller rewrites this to the stable ReplicaSet hash
    rollouts-pod-template-hash: stable
  ports:
  - name: http
    port: 80
    targetPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: hello-canary
  labels:
    app: hello
spec:
  selector:
    app: hello
    # Rollouts controller rewrites this to the canary ReplicaSet hash
    rollouts-pod-template-hash: canary
  ports:
  - name: http
    port: 80
    targetPort: 5678
