# envs/staging/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/apps/mesh-lab
- ../../base/security

namespace: mesh-lab-staging
nameSuffix: -staging

patches:
- path: rollout-patch.yaml

replacements:
# This block fixes the Rollout service names
- source:
    kind: Service
    name: hello-stable
    fieldPath: metadata.name
  targets:
  - select:
      kind: Rollout
      name: hello
    fieldPaths:
    - spec.strategy.canary.stableService
- source:
    kind: Service
    name: hello-canary
    fieldPath: metadata.name
  targets:
  - select:
      kind: Rollout
      name: hello
    fieldPaths:
    - spec.strategy.canary.canaryService
# ADD THIS BLOCK TO FIX THE VIRTUALSERVICE HOSTS
- source:
    kind: Service
    name: hello-stable
    fieldPath: metadata.name
  targets:
  - select:
      kind: VirtualService
      name: hello
    fieldPaths:
    - spec.http.0.route.0.destination.host
- source:
    kind: Service
    name: hello-canary
    fieldPath: metadata.name
  targets:
  - select:
      kind: VirtualService
      name: hello
    fieldPaths:
    - spec.http.0.route.1.destination.host
