apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/apps/mesh-lab # <-- Points to the shared app base
- ../../base/security     # <-- Points to the shared security base

namespace: mesh-lab-staging
nameSuffix: -staging


patches: # Using 'patches' instead of the deprecated 'patchesStrategicMerge'
- path: rollout-patch.yaml

replacements:
- source:
    kind: Service
    name: hello-stable
    fieldPath: metadata.name
  targets:
  - select:
      kind: Rollout
      name: hello
    fieldPaths:
    - spec.strategy.canary.stableService
- source:
    kind: Service
    name: hello-canary
    fieldPath: metadata.name
  targets:
  - select:
      kind: Rollout
      name: hello
    fieldPaths:
    - spec.strategy.canary.canaryService

- source:
    kind: Service
    name: hello-stable
    fieldPath: metadata.name
  targets:
  - select:
      kind: VirtualService
      name: hello
    fieldPaths:
    - spec.http.0.route.0.destination.host # <-- Updates the stable host route
- source:
    kind: Service
    name: hello-canary
    fieldPath: metadata.name
  targets:
  - select:
      kind: VirtualService
      name: hello
    fieldPaths:
    - spec.http.0.route.1.destination.host 
