apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- apps/mesh-lab/services.yaml
- apps/mesh-lab/virtualservice.yaml
- apps/mesh-lab/rollout.yaml
- apps/mesh-lab/analysis-template.yaml
- apps/mesh-lab/security/global-mtls.yaml
- apps/mesh-lab/security/hello-auth-policy.yaml

patchesStrategicMerge:
- rollout-patch.yaml
