# envs/staging/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/apps/mesh-lab
- ../../base/security

namespace: mesh-lab-staging
nameSuffix: -staging

patches:
- path: rollout-patch.yaml
- path: vs-patch.yaml # <-- Use the new patch
