apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mesh-lab-dev
nameSuffix: -dev
resources:
- ../../base/apps/mesh-lab
- ../../base/security
- ../../base/platform
patches:
- path: rollout-patch.yaml
  target:
    kind: Rollout
    name: hello
- path: vs-patch.yaml
  target:
    kind: VirtualService
    name: hello
