apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/apps/mesh-lab # <-- Points to the shared app base
- ../../base/security     # <-- Points to the shared security base
- ../../base/platform

namespace: mesh-lab-dev
nameSuffix: -dev


# ADD THIS ENTIRE 'replacements' BLOCK
replacements:
- source:
    kind: Service
    name: hello-stable
    fieldPath: metadata.name
  targets:
  - select:
      kind: Rollout
      name: hello
    fieldPaths:
    - spec.strategy.canary.stableService
- source:
    kind: Service
    name: hello-canary
    fieldPath: metadata.name
  targets:
  - select:
      kind: Rollout
      name: hello
    fieldPaths:
    - spec.strategy.canary.canaryService
