# envs/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/apps/mesh-lab
- ../../base/security
- ../../base/platform

namespace: mesh-lab-dev # <-- This will isolate the environment
