apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/apps/mesh-lab # <-- Points to the shared app base
- ../../base/security     # <-- Points to the shared security base
